Timor-Chat/
│── 📁 public/           → (Frontend)
│   ├── 📄 index.html     → (Tampilan Chatbot)
│   ├── 📄 styles.css     → (Desain Chatbot)
│   ├── 📄 script.js      → (Frontend Chatbot)
│── 📁 backend/          → (Backend LLaMA & DALL·E)
│   ├── 📄 main.py        → (FastAPI untuk AI Chatbot)
│   ├── 📄 requirements.txt → (Library Python)
│── 📄 .gitignore        → (File yang diabaikan)
│── 📄 README.md         → (Dokumentasi)
│── 📄 package.json      → (Jika pakai Node.js)
